"""add cid to employment

Revision ID: 07eedaca0d9c
Revises: c181358dbec6
Create Date: 2018-04-18 21:52:47.854505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07eedaca0d9c'
down_revision = 'c181358dbec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employment', sa.Column('cid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employment', 'cid')
    # ### end Alembic commands ###
