"""add indexes to user

Revision ID: 11d46fda4d0d
Revises: 8e8f5d39ed15
Create Date: 2018-01-26 14:21:03.632920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11d46fda4d0d'
down_revision = '8e8f5d39ed15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_schoolid'), 'user', ['schoolid'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_schoolid'), table_name='user')
    # ### end Alembic commands ###
