"""change schoolid to string in usertable

Revision ID: 2e51659db58f
Revises: e68a363ed850
Create Date: 2018-01-26 15:01:17.208983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e51659db58f'
down_revision = 'e68a363ed850'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('schoolid', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_user_schoolid'), 'user', ['schoolid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_schoolid'), table_name='user')
    op.drop_column('user', 'schoolid')
    # ### end Alembic commands ###
