"""reset table club

Revision ID: 4f8305c921ee
Revises: ca3ebb3ab493
Create Date: 2018-03-18 20:02:24.047341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8305c921ee'
down_revision = 'ca3ebb3ab493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('chairman', sa.String(length=255), nullable=True),
    sa.Column('memberno', sa.Integer(), nullable=True),
    sa.Column('avatar', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('cid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club')
    # ### end Alembic commands ###
