"""add apply table

Revision ID: ada4ab94b810
Revises: 07eedaca0d9c
Create Date: 2018-04-30 11:55:46.659812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ada4ab94b810'
down_revision = '07eedaca0d9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apply',
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('apid', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('employmentid', sa.Integer(), nullable=True),
    sa.Column('activityid', sa.Integer(), nullable=True),
    sa.Column('applytype', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('filepath', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('apid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apply')
    # ### end Alembic commands ###
