"""add table employment

Revision ID: c181358dbec6
Revises: 7296546483f4
Create Date: 2018-04-16 23:38:43.162461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c181358dbec6'
down_revision = '7296546483f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employment',
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('interview_time', sa.Date(), nullable=True),
    sa.Column('interview_address', sa.String(length=1024), nullable=True),
    sa.Column('resume_file', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('eid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employment')
    # ### end Alembic commands ###
