"""add login_token , last_update_login_token

Revision ID: c1f2536a50ec
Revises: 2e51659db58f
Create Date: 2018-01-29 22:50:38.158067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1f2536a50ec'
down_revision = '2e51659db58f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_update_login_token', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('login_token', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'login_token')
    op.drop_column('user', 'last_update_login_token')
    # ### end Alembic commands ###
