"""add base info fileds of user

Revision ID: c4e0158aabca
Revises: c1f2536a50ec
Create Date: 2018-03-06 10:02:47.760027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e0158aabca'
down_revision = 'c1f2536a50ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('user', sa.Column('campus', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('gender', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    op.drop_column('user', 'email')
    op.drop_column('user', 'campus')
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
