"""add club_admin

Revision ID: ca3ebb3ab493
Revises: 939fddea57f5
Create Date: 2018-03-18 10:20:47.272876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca3ebb3ab493'
down_revision = '939fddea57f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('cid', sa.Integer(), nullable=False))
    op.drop_column('club', 'aid')
    op.add_column('club_admin', sa.Column('cid', sa.Integer(), nullable=True))
    op.add_column('club_admin', sa.Column('uid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club_admin', 'uid')
    op.drop_column('club_admin', 'cid')
    op.add_column('club', sa.Column('aid', mysql.INTEGER(display_width=11), nullable=False))
    op.drop_column('club', 'cid')
    # ### end Alembic commands ###
