"""drop schoolid

Revision ID: e68a363ed850
Revises: 11d46fda4d0d
Create Date: 2018-01-26 15:00:30.280503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e68a363ed850'
down_revision = '11d46fda4d0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_schoolid', table_name='user')
    op.drop_column('user', 'schoolid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('schoolid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_index('ix_user_schoolid', 'user', ['schoolid'], unique=False)
    # ### end Alembic commands ###
