"""add clubid to apply

Revision ID: ef86b3c13081
Revises: ada4ab94b810
Create Date: 2018-05-01 23:01:29.715954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef86b3c13081'
down_revision = 'ada4ab94b810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apply', sa.Column('clubid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apply', 'clubid')
    # ### end Alembic commands ###
